version: '3.1'

services:

  pg:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-tier
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.5
    restart: always
    networks:
      - app-tier
    ports:
      - 8080:8080

networks:
  app-tier:
    driver: bridge