version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo:4.2.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - app-tier
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.49
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - app-tier
    ports:
      - 8081:8081
    depends_on:
      - mongo

networks:
  app-tier:
    driver: bridge